### ISSUE TITLE
Include version element for use in Citation?

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/cioos-siooc-metadata-profile#1]
There' no space for a version number for the data in the CIOOS metadata profile but it could go in MD_DataIdentification.citation.CI_Citation.edition according to ESIP Data Citation Guidelines. This would be useful for versioning datasets using the 'snapshot' approach.

**Comment by n-a-t-e** [comment]
This is how it would look in ISO 19115-3. I noticed theres also an optional `editionDate` field, which must be a datetime.

In `/mdb:MD_Metadata/mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation`:

```xml
...
</cit:date>	

<cit:edition>
    <gco:CharacterString>version 1.23</gco:CharacterString>
</cit:edition>

<cit:editionDate>
    <gco:DateTime>2020-03-07T02:02:22Z</gco:DateTime>
</cit:editionDate>
```

**Comment by n-a-t-e** [comment]
This refers to versioning of the metadata record:

`edition`  will come from a free form text field in the metadata form

`editionDate` would be last edited date that is already stored in the record

**Comment by Br-Johnson** [comment]
transferred to metadata-entry-from repo
